version: 2
jobs:
  build:
    machine: true
    #docker:
    #  - image: circleci/hello-ci-workflow:1.0
    steps:
      - checkout
      #- run: echo "hello world"
      - run: docker build -t circleci/hello-ci-workflow:1.0 .
  test:
    machine: true
    steps:
      - docker run -d -p 3000:3000 circleci/hello-ci-workflow:1.0; sleep 10
      - curl --retry 10 --retry-delay 5 -v http://localhost:3000
      
    

workflows:
  version: 2
  build:
    jobs:
      - build
      - test